package com.haodaone.remotesupport.entity;

public enum RemoteSupportStatus {
    QUEUED, DOWNLOADING, INSTALLING, CONFIGURING, PASSWORD_CONFIGURED, RUNNING, VERIFYING, READY, FAILED, DEVICE_OFFLINE, NOT_INSTALLED, UNSUPPORTED_AUTOMATION, CANCELLED, DISABLED
}